### ISSUE TITLE
README.md missing issues

### ISSUE THREAD

**Issue by PokeOwo** [Akascape/Vdo-Img-Conversion-Tools#3]
Please add in README.md : 

"Make sure you have opencv-python and customtkinter and packaging installed."

**Comment by Akascape** [comment]
@PokeOwo I know this is a issue because packaging module was removed from default packages after python 3.11, it is actually needed by customtkinter.

And I know it should be added to the setup file of customtkinter so that it gets installed automatically with customtkinter. But the owner of customtkinter is really inactive and hardly gives any update.
